### PR TITLE
#162100162 ft user profile 

### PR DESCRIPTION
**Pull request by kirega**
#### What does this PR do?
It adds the dashboard page for users to get a quick overview of all the incidences they have added.
#### Description of Task to be completed?
-It creates a set of cards to show the number of incidences in the respective statuses
- A table to show the users list of incidences
- If it was an admin login it would show all the incidences for everyone
#### How should this be manually tested?
Clone the repo 
Open index.html  on browser
Navigate to login ->dashboard
#### What are the relevant pivotal tracker stories?
#162100162
#### Screenshots (if appropriate)
image
image

### CODE REVIEW

**Comment by xcixor** [comment]
great design and responsiveness, as an improvement you can make the name, type and description of each record to display as rows and not columns so that they dont compress

**Comment by kirega** [comment]
@xcixor  The table at the bottom is horizontally scrollable. Making it vertical would be hard to read.
What do you think?

**Comment by LarryKarani** [comment]
good design awesome data representation

**Comment by xcixor** [comment]
@kirega , you could represent each record on its own as, record1 {name, type, description....}, record2 {name, type, description....}, though it sounds repetitive it might be better user experience

**Comment by kirega** [comment]
@xcixor I can not quite understand that layout.
Maybe a visual tomorrow  will help

**Comment by macymuhia** [comment]
Beautiful design, I think it gives a good summary in one page

**Pull request merged**
